target 'Cigars' do
  use_frameworks! :linkage => :static
  inherit! :search_paths
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'FirebaseCore'
  pod 'FirebaseDatabase'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseInstallations'
  pod 'FirebasePerformance'
  pod 'FirebaseMessaging'
  
  post_install do |installer|
        installer.pods_project.targets.each do |target|        
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
          end
        end
      end
end
