[versions]
agp = "8.4.0-alpha03"
kotlin = "1.9.20"
compose = "1.5.4"
compose-compiler = "1.5.4"
compose-material3 = "1.1.2"
androidx-activityCompose = "1.8.2"

jetbrains-compose-version = "1.5.10"

moko-compose-version = "0.23.0"
moko-resources-version = "0.22.2"

i18n-version = "0.6.2"
napier-version = "2.6.1"
locale-version = "0.5.0"

voyagerNavigator = "1.0.0-rc08"
mvvmCompose = "0.16.1"
mvvmCore = "0.16.1"
moko-mvvm-version = "0.16.0"

sqldelight-version = "2.1.0-SNAPSHOT"
sqldelight-plugin-version = "2.1.0-SNAPSHOT"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources-version" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources-version" }
napier = { module = "io.github.aakira:napier", version.ref = "napier-version" }
i18n = { module = "de.comahe.i18n4k:i18n4k-core", version.ref = "i18n-version" }
locale = { module = "com.vanniktech:multiplatform-locale", version.ref = "locale-version" }
voyager-bottom-sheet-navigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyagerNavigator" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerNavigator" }
voyager-tab-navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyagerNavigator" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyagerNavigator" }
mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "mvvmCore" }
mvvm-flow = { module = "dev.icerock.moko:mvvm-flow", version.ref = "mvvmCore" }
mvvm-flow-compose = { module = "dev.icerock.moko:mvvm-flow-compose", version.ref = "mvvmCompose" }
mvvm-flow-resources = { module = "dev.icerock.moko:mvvm-flow-resources", version.ref = "mvvmCore" }
mvvm-livedata = { module = "dev.icerock.moko:mvvm-livedata", version.ref = "mvvmCore" }
mvvm-livedata-compose = { module = "dev.icerock.moko:mvvm-livedata-compose", version.ref = "mvvmCompose" }
mvvm-livedata-resources = { module = "dev.icerock.moko:mvvm-livedata-resources", version.ref = "mvvmCore" }
mvvm-state = { module = "dev.icerock.moko:mvvm-state", version.ref = "mvvmCore" }
moko-mvvm = { module = "dev.icerock.moko:mvvm-compose", version.ref = "moko-mvvm-version" }
sqldelight-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight-plugin-version" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight-version" }
sqldelight-ios = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight-version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinSerialization = { id = "plugin.serialization", version.ref = "kotlin" }
i18n = { id = "de.comahe.i18n4k", version.ref = "i18n-version" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose-version" }
mokoCompose = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-compose-version" }
